spring.application.name=wedding-app
# Cloudinary Configuration
cloudinary.cloud-name=CLOUDINARY_CLOUD_NAME
cloudinary.api-key=CLOUDINARY_API_KEY
cloudinary.api-secret=CLOUDINARY_API_SECRET
# ... (rest of your NEON DB)
spring.datasource.url=jdbc:postgresql://ep-summer-cell-a16hqwcc-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=NEONDB_PASSKEY
spring.datasource.driver-class-name=org.postgresql.Driver

# Tells Spring Boot to use Postgres SQL syntax
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# CRUCIAL: This tells Spring Boot to automatically create your gallery_images table!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Allow larger photo uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB