spring.application.name=wedding-app
# Cloudinary Configuration
cloudinary.cloud-name=djgwsau9m
cloudinary.api-key=528439219119298
cloudinary.api-secret=k8e2a7DENYfGj4hCBQTIPKYFOoU
# ... (rest of your NEON DB)
spring.datasource.url=jdbc:postgresql://ep-summer-cell-a16hqwcc-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_uhmpH9vG6lMr
spring.datasource.driver-class-name=org.postgresql.Driver

# Tells Spring Boot to use Postgres SQL syntax
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# CRUCIAL: This tells Spring Boot to automatically create your gallery_images table!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Allow larger photo uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB